package fr.elias.morecreeps.common.advancements;

import fr.elias.morecreeps.common.Reference;
import net.minecraft.advancements.AdvancementList;
import net.minecraft.stats.Stat;
import net.minecraft.util.ResourceLocation;

public class ModAdvancementList extends AdvancementList
{
	public static ResourceLocation FRISBEE = new ResourceLocation(Reference.MODID + "advancements/frisbee.json");
    public static ResourceLocation radio = new ResourceLocation(Reference.MODID + "advancements/radio.json");
    public static ResourceLocation gotohell = new ResourceLocation(Reference.MODID + "advancements/gotohell");
    public static ResourceLocation chugcola = new ResourceLocation(Reference.MODID + "advancements/chugcola");
    public static ResourceLocation pigtaming = new ResourceLocation(Reference.MODID + "advancements/pigtaming");
    public static ResourceLocation piglevel5 = new ResourceLocation(Reference.MODID + "advancements/piglevel5");
    public static ResourceLocation piglevel10 = new ResourceLocation(Reference.MODID + "advancements/piglevel10");
    public static ResourceLocation piglevel20 = new ResourceLocation(Reference.MODID + "advancements/piglevel20");
    public static ResourceLocation rocketgiraffe = new ResourceLocation(Reference.MODID + "advancements/rocketgiraffe");
    public static ResourceLocation rocket = new ResourceLocation(Reference.MODID + "advancements/rocket");
    public static ResourceLocation rocketrampage = new ResourceLocation(Reference.MODID + "advancements/rocketrampage");
    public static ResourceLocation pyramid = new ResourceLocation(Reference.MODID + "advancements/pyramid");
    public static ResourceLocation floobkill = new ResourceLocation(Reference.MODID + "advancements/floobkill");
    public static ResourceLocation floobicide = new ResourceLocation(Reference.MODID + "advancements/floobicide");
    public static ResourceLocation gookill = new ResourceLocation(Reference.MODID + "advancements/gookill");
    public static ResourceLocation gookill10 = new ResourceLocation(Reference.MODID + "advancements/gookill10");
    public static ResourceLocation gookill25 = new ResourceLocation(Reference.MODID + "advancements/gookill25");
    public static Advancement snowdevil = new ResourceLocation(Reference.MODID + "advancements/snowdevil");
    public static ResourceLocation hunchback;
    public static ResourceLocation rockmonster;
    public static ResourceLocation bumflower;
    public static ResourceLocation bumpot;
    public static ResourceLocation bumlava;
    public static ResourceLocation one_hundred_bucks;
    public static ResourceLocation five_hundred_bucks;
    public static ResourceLocation one_thousand_bucks;
    public static ResourceLocation pighotel;
    public static ResourceLocation ten_bubble;
    public static ResourceLocation twenty_five_bubble;
    public static ResourceLocation fifty_bubble;
    public static ResourceLocation one_hundred_bubble;
    public static ResourceLocation snow;
    public static ResourceLocation snowtiny;
    public static ResourceLocation snowtall;
    public static ResourceLocation hotdoglevel5;
    public static ResourceLocation hotdoglevel10;
    public static ResourceLocation hotdoglevel25;
    public static ResourceLocation hotdogheaven;
    public static ResourceLocation hotdogtaming;
    public static ResourceLocation ram128;
    public static ResourceLocation ram512;
    public static ResourceLocation ram1024;
    public static ResourceLocation falseidol;
    public static ResourceLocation camel;
    public static ResourceLocation lolliman;
    public static ResourceLocation zebra;
    public static ResourceLocation schlump;
    public static ResourceLocation nonswimmer;
    public static ResourceLocation prisoner;
    public static ResourceLocation five_prisoner;
    public static ResourceLocation ten_prisoner;
    public static ResourceLocation one_caveman;
    public static ResourceLocation ten_caveman;
    public static ResourceLocation fifty_caveman;
}
